# Generated by Django 6.0.3 on 2026-03-22 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_refine_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulematerial',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_old', to='core.module'),
        ),
        migrations.CreateModel(
            name='ModuleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(default='New Week', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.module')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('module', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='modulematerial',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.moduleweek'),
        ),
    ]
