# Generated by Django 6.0.3 on 2026-03-22 05:54

from django.db import migrations


def populate_module_weeks(apps, schema_editor):
    Module = apps.get_model('core', 'Module')
    ModuleWeek = apps.get_model('core', 'ModuleWeek')
    ModuleMaterial = apps.get_model('core', 'ModuleMaterial')

    for module in Module.objects.all():
        week, created = ModuleWeek.objects.get_or_create(
            module=module,
            week_number=1,
            defaults={'title': 'Week 1 - General Materials'}
        )
        for material in ModuleMaterial.objects.filter(module=module):
            material.week = week
            material.save()

def revert_module_weeks(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_modulematerial_module_moduleweek_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_module_weeks, revert_module_weeks),
    ]
